/////////////////////////////////////////////////////////////////////////////
// Name:        SplitPictureToolGuiFrame.cpp
// Purpose:     
// Author:      ChenBK
// Modified by: 
// Created:     25/06/2016 23:52:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 25/06/2016 23:52:48

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "SplitPictureToolGuiFrame.h"

////@begin XPM images
////@end XPM images


/*
 * SplitPictureToolGuiFrame type definition
 */

IMPLEMENT_CLASS( SplitPictureToolGuiFrame, wxFrame )


/*
 * SplitPictureToolGuiFrame event table definition
 */

BEGIN_EVENT_TABLE( SplitPictureToolGuiFrame, wxFrame )

////@begin SplitPictureToolGuiFrame event table entries
////@end SplitPictureToolGuiFrame event table entries

END_EVENT_TABLE()


/*
 * SplitPictureToolGuiFrame constructors
 */

SplitPictureToolGuiFrame::SplitPictureToolGuiFrame()
{
    Init();
}

SplitPictureToolGuiFrame::SplitPictureToolGuiFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create( parent, id, caption, pos, size, style );
}


/*
 * SplitPictureToolGuiFrame creator
 */

bool SplitPictureToolGuiFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin SplitPictureToolGuiFrame creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end SplitPictureToolGuiFrame creation
    return true;
}


/*
 * SplitPictureToolGuiFrame destructor
 */

SplitPictureToolGuiFrame::~SplitPictureToolGuiFrame()
{
////@begin SplitPictureToolGuiFrame destruction
////@end SplitPictureToolGuiFrame destruction
}


/*
 * Member initialisation
 */

void SplitPictureToolGuiFrame::Init()
{
////@begin SplitPictureToolGuiFrame member initialisation
////@end SplitPictureToolGuiFrame member initialisation
}


/*
 * Control creation for SplitPictureToolGuiFrame
 */

void SplitPictureToolGuiFrame::CreateControls()
{    
////@begin SplitPictureToolGuiFrame content construction
    // Generated by DialogBlocks, 26/06/2016 04:07:38 (unregistered)

    SplitPictureToolGuiFrame* itemFrame1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    itemFrame1->SetSizer(itemBoxSizer2);

    wxButton* itemButton3 = new wxButton( itemFrame1, ID_BUTTON, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer2->Add(itemButton3, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton4 = new wxButton( itemFrame1, ID_BUTTON1, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer2->Add(itemButton4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end SplitPictureToolGuiFrame content construction
}


/*
 * Should we show tooltips?
 */

bool SplitPictureToolGuiFrame::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap SplitPictureToolGuiFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin SplitPictureToolGuiFrame bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end SplitPictureToolGuiFrame bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon SplitPictureToolGuiFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin SplitPictureToolGuiFrame icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end SplitPictureToolGuiFrame icon retrieval
}
