/////////////////////////////////////////////////////////////////////////////
// Name:        SplitPictureToolGuiFrame.h
// Purpose:     
// Author:      ChenBK
// Modified by: 
// Created:     25/06/2016 23:52:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 25/06/2016 23:52:48

#ifndef _SPLITPICTURETOOLGUIFRAME_H_
#define _SPLITPICTURETOOLGUIFRAME_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_SPLITPICTURETOOLGUIFRAME 10000
#define ID_BUTTON 10001
#define ID_BUTTON1 10002
#define SYMBOL_SPLITPICTURETOOLGUIFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_SPLITPICTURETOOLGUIFRAME_TITLE _("SplitPictureToolGuiFrame")
#define SYMBOL_SPLITPICTURETOOLGUIFRAME_IDNAME ID_SPLITPICTURETOOLGUIFRAME
#define SYMBOL_SPLITPICTURETOOLGUIFRAME_SIZE wxSize(400, 300)
#define SYMBOL_SPLITPICTURETOOLGUIFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * SplitPictureToolGuiFrame class declaration
 */

class SplitPictureToolGuiFrame: public wxFrame
{    
    DECLARE_CLASS( SplitPictureToolGuiFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    SplitPictureToolGuiFrame();
    SplitPictureToolGuiFrame( wxWindow* parent, wxWindowID id = SYMBOL_SPLITPICTURETOOLGUIFRAME_IDNAME, const wxString& caption = SYMBOL_SPLITPICTURETOOLGUIFRAME_TITLE, const wxPoint& pos = SYMBOL_SPLITPICTURETOOLGUIFRAME_POSITION, const wxSize& size = SYMBOL_SPLITPICTURETOOLGUIFRAME_SIZE, long style = SYMBOL_SPLITPICTURETOOLGUIFRAME_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_SPLITPICTURETOOLGUIFRAME_IDNAME, const wxString& caption = SYMBOL_SPLITPICTURETOOLGUIFRAME_TITLE, const wxPoint& pos = SYMBOL_SPLITPICTURETOOLGUIFRAME_POSITION, const wxSize& size = SYMBOL_SPLITPICTURETOOLGUIFRAME_SIZE, long style = SYMBOL_SPLITPICTURETOOLGUIFRAME_STYLE );

    /// Destructor
    ~SplitPictureToolGuiFrame();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin SplitPictureToolGuiFrame event handler declarations

////@end SplitPictureToolGuiFrame event handler declarations

////@begin SplitPictureToolGuiFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end SplitPictureToolGuiFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin SplitPictureToolGuiFrame member variables
////@end SplitPictureToolGuiFrame member variables
};

#endif
    // _SPLITPICTURETOOLGUIFRAME_H_
